repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["src/"]
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: ["src/"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: ["src/"]
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.4'
    hooks:
    - id: bandit
      args: ["-c", "bandit.yaml","-r", "src/"]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy
        # args: ["--config-file=mypy.ini"]
        language: system
        types: [python]
        args: ["src/"]
