version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - JAEGER_OTLP_GRPC_ENDPOINT=jaeger:4317
      - JAEGER_OTLP_HTTP_ENDPOINT=http://jaeger:4318/v1/traces
      - JAEGER_MODE=otlp-grpc
      - JAEGER_SERVICE_NAME=fastapi-app
    depends_on:
      - jaeger
    networks:
      - fastapi_net
    volumes:
      - .:/app

  jaeger:
    image: jaegertracing/all-in-one:1.50
    container_name: jaeger
    ports:
      - "16686:16686"  # UI
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - fastapi_net
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - fastapi_net
    depends_on:
      - app
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./graphana/dashboards:/etc/grafana/provisioning/dashboards/dashboards
      - ./graphana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./graphana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SECURITY_ADMIN_PASSWORD=admin  # optional: in case login is still needed
    depends_on:
      - prometheus
    networks:
      - fastapi_net


volumes:
  grafana-storage:

networks:
  fastapi_net:
    driver: bridge
