version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - JAEGER_OTLP_GRPC_ENDPOINT=jaeger:4317
      - JAEGER_OTLP_HTTP_ENDPOINT=http://jaeger:4318/v1/traces
      - JAEGER_MODE=otlp-grpc
      - JAEGER_SERVICE_NAME=fastapi-app
    depends_on:
      - jaeger
    networks:
      - fastapi_net
    volumes:
      - .:/app

  jaeger:
    image: jaegertracing/all-in-one:1.50
    container_name: jaeger
    ports:
      - "16686:16686"  # UI
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - fastapi_net

networks:
  fastapi_net:
    driver: bridge
