name: CICD PIPELINE
# CICD PIPELINE : Build, Push Docker Image, and Deploy to Azure
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  DOCKER_IMAGE: ${{ secrets.DOCKER_REPO }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbqa black flake8 isort sqlfluff bandit

      - name: Run linters
        run: |
          black src/ tests/
          isort src/ tests/
          flake8 src/ tests/
          nbqa black src/ tests/
          nbqa flake8 src/ tests/
          nbqa isort src/ tests/
          sqlfluff lint src/ tests/
      
      - name: Run bandit security checks
        run: |
          bandit  -r src/
          
  ai-review:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run AI Code Review Agent
        uses: Manav-Khandurie/agents/code-review-agent@code-review-agent-v1.0.4 # Stable tested 1.0.3
        with:
          config-path: "./ai-review.yaml"
          score-threshold: 85
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
  
  build-and-push:
    runs-on: ubuntu-latest
    needs: ai-review
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      # Extract version
      - name: Extract version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          SHORT_SHA=$(git rev-parse --short HEAD)
          if [[ "$VERSION" == "main" ]]; then
            VERSION="dev-${SHORT_SHA}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ steps.version.outputs.version }} .

      # Tag Docker image as latest
      - name: Docker image tag latest
        run: |
          docker tag ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ steps.version.outputs.version }} ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest

      # Push Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ steps.version.outputs.version }}
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest

  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-push  # This ensures the deploy job runs only after the build-and-push job succeeds

    steps:
      # Checkout repository again for this job
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Check Azure CLI version
      - name: Check Azure CLI version
        run: az --version

      # Deploy Docker image from DockerHub to Azure Web App
      - name: Deploy Docker image from DockerHub to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest

      # Get Web App URL
      - name: Get Web App URL
        run: |
          url=$(az webapp show --name $AZURE_WEBAPP_NAME --resource-group $AZURE_RESOURCE_GROUP --query defaultHostName -o tsv)
          echo "App URL: https://$url"
