# .github/workflows/docker-build-psh.yaml
name: Docker Build and Push

on:
  workflow_call: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.version.outputs.version }}  # pass version/tag

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/*/}
        SHORT_SHA=$(git rev-parse --short HEAD)
        if [[ "$VERSION" == "main" ]]; then
          VERSION="dev-${SHORT_SHA}"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build and Tag Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{ steps.version.outputs.version }} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{ steps.version.outputs.version }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{ steps.version.outputs.version }}
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest
